nodeLinker: node-modules

# prettier-ignore
packageExtensions:
  "@nrwl/devkit@^15":
    dependencies:
      nx: ^15
  postcss-cssnext@^3.1.0:
    dependencies:
      caniuse-lite: ^1
  source-map-loader@^4:
    dependencies:
      webpack: ^5
